### ISSUE TITLE
Issue de test pour le board

### ISSUE THREAD

**Issue by wytrem** [SalonDesDevs/SuperDungeonsDestroyers#1]
Mais où est donc Ornicar ?

**Comment by wytrem** [comment]
Test de cloture.

**Comment by wytrem** [comment]
Test de réouverture.

**Comment by TheElectronWill** [comment]
wow

**Comment by wytrem** [comment]
Un problème ? 🍭

**Comment by MinusKube** [comment]
My god everything's in french, I don't understand anything, please speak english :3

**Comment by wytrem** [comment]
Back to your Minecraft modding stuff. 🌵
